print("Hello! Our team is building a project together.")
print("This is our first shared GitHub project.")
print("Feature added by Member 2!")
print("Feature 2: Our team collaboration works!")
print("Feature 3: Added by Member 1!")
print("This feature is being developed on a separate branch.")
print("Feature 4: Ready for our hackathon project!")